// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapdayController from "./mapday_controller"
application.register("mapday", MapdayController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import SummaryController from "./summary_controller"
application.register("summary", SummaryController)


import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
